### ISSUE TITLE
Requested module node:crypto does not provide an export named webcrypto

### ISSUE THREAD

**Issue by nortenootaku** [zhuowei/TweetbotLoginProxy#3]
i have this issue while trying to use this:
SyntaxError: The requested module 'node:crypto' does not provide an export named 'webcrypto'
how i can solve this
im using windows 10 with windows subsystem for linux

**Comment by nortenootaku** [comment]
i think i solved these problem but another one showed
  const hashedKey = await subtle.digest('SHA-256', key);
                                 ^

TypeError: Cannot read property 'digest' of undefined
    at encodeTweetbot (file:///mnt/c/Users/user1/Z/G/index.js:28:34)
    at file:///mnt/c/Users/user1/Z/G/index.js:22:37
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
    at async handleMainPromise (internal/modules/run_main.js:59:12)
i hope you can help me
